services:
  postgres:
    image: postgres:16
    container_name: projectpulse-postgres
    environment:
      POSTGRES_DB: projectpulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - projectpulse_postgres_data:/var/lib/postgresql/data

volumes:
  projectpulse_postgres_data:
